//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//using Cirrious.MvvmCross.Community.Plugins.Sqlite;
using SQLite.Net.Attributes;

namespace MLearningDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumer_by_circle
    {
		[PrimaryKey, AutoIncrement]
		public int id_pk { get; set;}
        public int id { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string fullname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string image_url { get; set; }
        public int is_online { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int Circle_id { get; set; }
    }
}
