//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLearning.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class head_by_institution
    {
        public int id { get; set; }
        public int head_id { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string fullname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int institution_id { get; set; }
        public string institution_name { get; set; }
        public string country { get; set; }
        public string region { get; set; }
        public string address_line_1 { get; set; }
        public string city { get; set; }
        public int postal_code { get; set; }
        public int telephone { get; set; }
        public string email { get; set; }
        public string website_address { get; set; }
        public string notes { get; set; }
        public System.DateTime updated_at { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime iupdated_at { get; set; }
        public System.DateTime icreated_at { get; set; }
    }
}
