//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//using Cirrious.MvvmCross.Community.Plugins.Sqlite;
using SQLite.Net.Attributes;

namespace MLearningDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
		[PrimaryKey, AutoIncrement]
		public int id_pk { get; set;}
        public int id { get; set; }
        public string description { get; set; }
        public string url_img { get; set; }
        public string content { get; set; }
        public int lo_id { get; set; }
        public bool C__deleted { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string title { get; set; }
        public int LOsection_id { get; set; }
    
    }

    public class JsonPage
    {
        public string description { get; set; }
        public string title { get; set; }
        public string xml_content { get; set; }

        public string url_img { get; set; }
    }
}
