//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//using Cirrious.MvvmCross.Community.Plugins.Sqlite;
using SQLite.Net.Attributes;

namespace MLearningDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class quiz_by_circle
    {
		[PrimaryKey, AutoIncrement]
		public int id_pk { get; set;}
        public int id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int LearningObject_id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public int circle_id { get; set; }
        public string qualification { get; set; }
        public Nullable<int> User_id { get; set; }
    }
}
